using DevExpress.XtraGrid.Views.Base;
using DevExpress.XtraGrid.Views.Grid;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Globalization;
using System.Linq;
using System.Windows.Forms;
using DevExpress.Utils;
using DevExpress.Utils.Extensions;
using DevExpress.XtraBars;
using DevExpress.XtraEditors;
using DevExpress.XtraEditors.Controls;
using DevExpress.XtraEditors.Repository;
using DevExpress.XtraGrid;
using SRUL.Types;

namespace SRUL
{
    // TODO: Refactor SharedEvent to own Class, so not clutered
    // TODO: Form Class supposed for using to init and placement
    public partial class XtraForm1 : DevExpress.XtraBars.ToolbarForm.ToolbarForm
    {
        // Information countryInfoTable = new Information(Loader.Rw);
        
        // Inherit from Loader Class
        // private JSONReader jsonReader = SRLoader.LoaderInstance.jr;
        // private SRReadWrite rw = SRLoaderForm._sr.LoaderInstance.rw;
        private SRMain jsonReader = SRLoaderForm._srLoader.jr;
        private SRLoader Loader = SRLoaderForm._srLoader;
        private SRReadWrite rw = SRLoaderForm._srLoader.rw;
        
        // Gridview Initiliazation
        private int gvCurrentRow;
        private bool gvCurrentEnabledState;
        private bool gvCurrentRowName;

        private IList<Feature> warfareList;
        private Feature ArmyEfficiency;
        private Feature ArmyActualStrength;
        private Feature ArmyCurrentStrength;
        private Feature ArmyMorale;
        private Feature ArmyExperience;
        private Feature ArmyGas;
        private Feature ArmySupply;
        private Feature UnitFuelCapacity;
        private Feature UnitSuppliesCapacity;
        private Feature ArmyActiveStaff;
        private Feature ArmyReserve;
        private Feature UnitClass;
        private bool _isNaval;
        public XtraForm1()
        {
            InitializeComponent();
            
            barsiBtmTrainerStatus.Caption = jsonReader.Data.SRFStatus ? "Active" : "Inactive";
            checkedListBoxControl1.Items.Add(WarfareArmyEnum.Heal);
            checkedListBoxControl1.Items.Add(WarfareArmyEnum.Rambo);
            checkedListBoxControl1.Items.Add(WarfareArmyEnum.Str2x);
            checkedListBoxControl1.Items.Add(WarfareArmyEnum.Str4x);
            checkedListBoxControl1.Items.Add(WarfareArmyEnum.GasSupply2x);
            checkedListBoxControl1.Items.Add(WarfareArmyEnum.GasSupply4x);

            // Set Data Source for each Category control
            gcCountry.DataSource = jsonReader.FeaturesCountry;
            gcResources.DataSource = jsonReader.FeaturesResources;
            gcWarfare.DataSource = jsonReader.FeaturesWarfare;
            gcCountry.ForceInitialize();
            gcResources.ForceInitialize();
            gcWarfare.ForceInitialize();

            gvLoad(gvWarfare);
            gvLoad(gvResources);
            gvLoad(gvCountry);

            Deactivate += FormDeactivate;

            // _Helper = new FlashedCellsHelper(gvResources);
            // gvResources.CellValueChanged += gvCellValueChanged;

            // This line of code is generated by Data Source Configuration Wizard
            // Fill a JsonDataSource asynchronously
            // JSONGameVersion.FillAsync();
        }

        private void gvLoad(GridView gv)
        {
            gv.OptionsMenu.EnableColumnMenu = false;
            gv.OptionsMenu.EnableFooterMenu = false;
            gv.OptionsCustomization.AllowSort = false;
            gv.OptionsView.ColumnAutoWidth = true;
            // initFlashCell(gv);
        }
        private void barButtonItem1_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {

        }

        private void barHeaderItem1_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {

        }

        void showHealthBar()
        {

            if (jsonReader.feature("UnitName").value == "") return;
            var UnitAct = jsonReader.feature("ArmyActualStrength");
            var UnitCur = jsonReader.feature("ArmyCurrentStrength");
            var UnitF = jsonReader.feature("ArmyGas");
            var UnitS = jsonReader.feature("ArmySupply");
            var UnitFCap = jsonReader.feature("UnitFuelCapacity");
            var UnitSCap = jsonReader.feature("UnitSuppliesCapacity");
            var UnitClass = jsonReader.feature("UnitClass").value;

            var UnitSupply = decimal.Parse(UnitS.value);
            var UnitFuel = decimal.Parse(UnitF.value);
            var UnitFuelCap = decimal.Parse(UnitFCap.value);
            var UnitSupplyCap = decimal.Parse(UnitSCap.value);
            var UnitCurrent = decimal.Parse(UnitCur.value);
            var UnitActual = decimal.Parse(UnitAct.value);

            // pbUnitHealthBar.Tag = "Health";
            // pbUnitFuelBar.Tag = "Fuel";
            // pbUnitSupplyBar.Tag = "Supply";
            
            if (rw.SRIsNaval(UnitClass.StrToInt()))
                UnitActual = UnitActual * 100;
            pbUnitHealthBar.Properties.Maximum = (int) UnitActual;
            pbUnitFuelBar.Properties.Maximum = (int) ((int) UnitCurrent * UnitFuelCap);
            pbUnitSupplyBar.Properties.Maximum = (int) UnitCurrent * (int) UnitSupplyCap;
            
            pbUnitHealthBar.EditValue = (int) UnitCurrent;
            pbUnitFuelBar.EditValue = (int) UnitFuel;
            pbUnitSupplyBar.EditValue = (int) UnitSupply;


            // pbUnitHealthBar.Tag = UnitF;
        }

        private void InitInfo()
        {
            SRInfo.Instance.SRDonationButton(btnDonate, TrainerEnum.Paypal);
            SRInfo.Instance.SRDonationButton(btnDonorBoxDonate, TrainerEnum.DonorBox);
            SRInfo.Instance.SRBarDonationHeader(barBtnDonation);
            SRInfo.Instance.SRBarDonationButton(barBtnDonationBottom);
            barHeaderVersion.Caption = Loader.currentProductVersion;
            barStaticItem1.Caption = $@"Game Version: {jsonReader.activeTrainer.GameVersion}";
            
            SRInfo.Instance.SRProductInformation(reInfo);
            SRInfo.Instance.SRChangeLog(reInfoChangelog);
        }
        private void XtraForm1_Load(object sender, EventArgs e)
        {
           InitInfo();
           warfareList = jsonReader.seekWarfareVariable(new []
           {
               "ArmyActiveStaff",
               "ArmyReserve",
               "ArmyActualStrength",
               "ArmyCurrentStrength",
               "ArmySupply",
               "ArmyFuel",
               "ArmyGas",
               "ArmyEfficiency",
               "ArmyExperience",
               "ArmyMorale",
               "UnitSuppliesCapacity",
               "UnitFuelCapacity",
               "UnitClass",
               "UnitMovementType",
               "UnitTargetType",
           });
           ArmyEfficiency = warfareList.Single(s => s.name == av.ArmyEfficiency.ToString());
           ArmyActualStrength = warfareList.Single(s => s.name == av.ArmyActualStrength.ToString());
           ArmyCurrentStrength = warfareList.Single(s => s.name == av.ArmyCurrentStrength.ToString());
           ArmyMorale = warfareList.Single(s => s.name == av.ArmyMorale.ToString());
           ArmyExperience = warfareList.Single(s => s.name == av.ArmyExperience.ToString());
           ArmyGas = warfareList.Single(s => s.name == av.ArmyGas.ToString());
           ArmySupply = warfareList.Single(s => s.name == av.ArmySupply.ToString());
           UnitFuelCapacity = warfareList.Single(s => s.name == av.UnitFuelCapacity.ToString());
           UnitSuppliesCapacity = warfareList.Single(s => s.name == av.UnitSuppliesCapacity.ToString());
           ArmyActiveStaff = warfareList.Single(s => s.name == av.ArmyActiveStaff.ToString());
           ArmyReserve = warfareList.Single(s => s.name == av.ArmyReserve.ToString());
           UnitClass = warfareList.Single(s => s.name == av.UnitClass.ToString());
           
           // this.LookAndFeel.SetSkinStyle(SkinStyle.VisualStudio2013Dark);
            // var s = skinPaletteDropDownButtonItem1.DropDownControl as GalleryDropDown
            // Enablind timer after datasource set
            mainTimer.Enabled = true;
            if(UnitClass.value != string.Empty)
                _isNaval = rw.SRIsNaval(Convert.ToInt32(UnitClass.value));
            //SpinEdit
            setContorlTag(seStaffActive, "ArmyActiveStaff");
            setContorlTag(seStaffReserve, "ArmyReserve");
            setContorlTag(seNavalStrActual, "ArmyActualStrength");
            setContorlTag(seNavalStrCurrent, "ArmyCurrentStrength");
            setContorlTag(seUnitStrActual, "ArmyActualStrength");
            setContorlTag(seUnitStrCurrent, "ArmyCurrentStrength");
            setContorlTag(seUnitFuel, "ArmyGas");
            setContorlTag(seUnitSupplies, "ArmySupply");
            //CheckEdit
            setContorlTag(ceEfficiency, "ArmyEfficiency");
            setContorlTag(ceExperience, "ArmyExperience");
            setContorlTag(ceMorale, "ArmyMorale");
            // setContorlTag(ceNavalStrength, "ArmyCurrentStrength,ArmyActualStrength");
            setContorlTag(ceUnitFuel, "ArmySupply");
            setContorlTag(ceUnitStrength, "ArmyCurrentStrength");
            setContorlTag(ceUnitSupplies, "ArmyGas");
            // setSpinEdit(new SpinEdit[]{seNavalStrActual, seNavalStrCurrent}, ceNavalStrength.Tag.CastTo<List<Feature>>());
            // setSpinEdit(new []{seUnitStrActual, seUnitStrCurrent}, ceUnitStrength.Tag.CastTo<List<Feature>>());

            // When changed then changed
            setSpinEditorEvent(seUnitStrActual);
            setSpinEditorEvent(seUnitStrCurrent);
            setSpinEditorEvent(seNavalStrActual);
            setSpinEditorEvent(seNavalStrCurrent);
            setSpinEditorEvent(seUnitFuel);
            setSpinEditorEvent(seUnitSupplies);
            setSpinEditorEvent(seStaffReserve);
            // Set Global Event for multiple control
            // gvCountry.ValidateRow += new ValidateRowEventHandler(gvValidateRow);
            // gvResources.ValidateRow += new ValidateRowEventHandler(gvValidateRow);
            // gvWarfare.ValidateRow += new ValidateRowEventHandler(gvValidateRow);

            // gvCountry.ShowingEditor += gvShowingEditor;
            // gvResources.ShowingEditor += gvShowingEditor;
            // gvWarfare.ShowingEditor += gvShowingEditor;

            // gvCountry.ShowingEditor += gvShowingEditor;
            // gvResources.ShowingEditor += gvShowingEditor;
            // gvWarfare.ShowingEditor += gvShowingEditor;

            // When DATASOURCE of Gridview is changed
            gvCountry.DataSourceChanged += gvDataSourceChanged;
            gvResources.DataSourceChanged += gvDataSourceChanged;
            gvWarfare.DataSourceChanged += gvDataSourceChanged;

            // Method to set gridview init events etc.
            setGvEvents(gvCountry);
            setGvEvents(gvResources);
            setGvEvents(gvWarfare);

            // Populate Combo box warfare unit value
            PopulateWarfareTypes(lookBoxUnitClass, WarfareValueDictionary.Instance.DictUnitClassType);
            PopulateWarfareTypes(lookBoxUnitMovementType, WarfareValueDictionary.Instance.DictUnitMovementType);
            PopulateWarfareTypes(lookBoxUnitTargetType, WarfareValueDictionary.Instance.DictUnitTargetType);

            // Sort Datagrid record Order based on SRUL.Types collection,
            // jsonReader.dgOrder(gvCountry);
            // jsonReader.dgOrder(gvResources);
            // jsonReader.dgOrder(gvWarfare);
            // gvWarfare.Columns["original"].Visible = true;
            
            //Hihlight
            gvHighlight(gvCountry);
            gvHighlight(gvResources);
            gvHighlight(gvWarfare);

            // gvCountry.FormatRules[0].Column = gvCountry.Columns["value"];

            // Custom Text Display Tonnes, $ sign, % when row is displayed
            // gvCountry.CustomColumnDisplayText += gvCustomColumnDisplayText;
            // gvWarfare.CustomColumnDisplayText += gvCustomColumnDisplayText;
            // gvResources.CustomColumnDisplayText += gvCustomColumnDisplayText;

            // gvCountry.CustomColumnSort += OnCustomColumnSort;
            
            // For Cell Editing custom, spinedit etc in a row.
            AddRepositoryItem(jsonReader.FeaturesCountry, gcCountry, gvCountry);
            AddRepositoryItem(jsonReader.FeaturesResources, gcResources, gvResources);
            AddRepositoryItem(jsonReader.FeaturesWarfare, gcWarfare, gvWarfare);
            
            // Flash Helper
            
            // SE percentage
            // SetSpinEditDisplayPercentage(seNavalStrActual);
            // SetSpinEditDisplayPercentage(seNavalStrCurrent);
            SetSpinEditDisplayPercentage(seNavalStrActual, true);
            SetSpinEditDisplayPercentage(seNavalStrCurrent, true);
            // pbUnitHealthBar.custom
            
            
            // Custom Display for HEALTH Bar, supposed to display overload value
            pbUnitHealthBar.Tag = "ArmyCurrentStrength";
            pbUnitFuelBar.Tag = "ArmyGas";
            pbUnitSupplyBar.Tag = "ArmySupply";
            pbUnitHealthBar.CustomDisplayText += SetProgressBarDisplayOverload;
            pbUnitFuelBar.CustomDisplayText += SetProgressBarDisplayOverload;
            pbUnitSupplyBar.CustomDisplayText += SetProgressBarDisplayOverload;
            
            // Special Warfare Option
            checkedListBoxControl1.ItemCheck += (sd, args) =>
            {
                CheckedListBoxControl clbc = sd as CheckedListBoxControl;
                var bl = clbc.Items[WarfareArmyEnum.Rambo].CheckState == CheckState.Checked;
                if (bl)
                {
                    ceEfficiency.Checked = true;
                    ceExperience.Checked = true;
                    ceMorale.Checked = true;
                }
                else
                {
                    ceEfficiency.Checked = false;
                    ceExperience.Checked = false;
                    ceMorale.Checked = false;
                }
            };
        }

        private void SetProgressBarDisplayOverload(object sender, CustomDisplayTextEventArgs e)
        {
            ProgressBarControl pbc = sender as ProgressBarControl;
            string unitSelected = jsonReader.feature("UnitSelected", jsonReader.FeaturesWarfare).value;
            Feature feature = jsonReader.feature(pbc.Tag.ToString(), jsonReader.FeaturesWarfare);
            // Feature realTag = pbc.Properties.Tag as Feature;
            if (pbc.Position == pbc.Properties.Maximum)
            {
                pbc.Position = pbc.Position - 1;
            }
            if (pbc != null && unitSelected.StrToInt() > 0)
            {
                if (pbc.Properties.Maximum == 0) return;
                if (pbc.Position == 0)
                {
                    e.DisplayText = "Empty";
                }
                // var tg = SystemExtension.StrToInt(pbc.Tag.ToString());
                var p = Convert.ToDouble(Convert.ToDecimal(feature.value) /
                                         Convert.ToDecimal(pbc.Properties.Maximum.ToString()));
                // if (pbc.Position == 0 && pbc.Properties.Maximum > 0) return;
                // if (pbc.Position >= pbc.Properties.Maximum)
                // {
                // memoEdit1.EditValue += pbc.Name + "\n"; 
                // memoEdit1.EditValue += pbc.Position.ToString() + "\n";
                // memoEdit1.EditValue += pbc.Properties.Maximum.ToString() + "\n\n";
                e.DisplayText = String.Format("{0:P1}", p);
            }
            // e.DisplayText = pbc.Position.ToString();
            // }

        }

        private void SetSpinEditDisplayPercentage(SpinEdit se, bool isNaval)
        {
            if (isNaval)
            {
                se.Properties.Increment = 1;
                se.Properties.IsFloatValue = true;
                se.Properties.DisplayFormat.FormatType = FormatType.Numeric;
                se.Properties.DisplayFormat.FormatString = "P";
                se.Properties.Mask.EditMask = "p";  
            }
            else
            {
                se.Properties.Increment = 10;
                se.Properties.IsFloatValue = false;
                se.Properties.Mask.EditMask = default;
                se.Properties.DisplayFormat.FormatType = default;
                se.Properties.DisplayFormat.FormatString = default;
            }
        }

        private void setGvEvents(GridView gv) 
        {
            // Set Global Event for multiple control, SR Write when validated.
            gv.ValidateRow += gvValidateRow;
            // When editor is showing, change ?
            gv.ShowingEditor += gvShowingEditor;
            // When DATASOURCE of Gridview is changed
            gv.DataSourceChanged += gvDataSourceChanged;
            // Custom Text Display Tonnes, $ sign, % when row is displayed
            gv.CustomColumnDisplayText += gvCustomColumnDisplayText;
            // Set Custom Row Filter for Warfare;
            gv.CustomRowFilter += jsonReader.gvRowFilterExclusion;
            // Sort Datagrid record Order based on SRUL.Types collection,
            jsonReader.dgOrder(gv);
        }
        private void gvCellValueChanged(object sender, CellValueChangedEventArgs e)
        {
            GridView view = sender as GridView;
            // int speed = (int) e.Value;
            view.RefreshData();
        } 

        private void AddRepositoryItem(IList<Feature> fs, GridControl gc, GridView gv)
        {
            RepositoryItemSpinEdit spin = new RepositoryItemSpinEdit();
            RepositoryItemLookUpEdit lookUp = new RepositoryItemLookUpEdit();
            gc.RepositoryItems.AddRange( new RepositoryItem[] { spin, lookUp });
            
            // Set Spin Properties
            spin.AllowMouseWheel = true;
            spin.AllowNullInput = DefaultBoolean.False;
            spin.ValidateOnEnterKey = true;
            
            // foreach (var feature in fs)
            // {
            //     if (feature.format == "percentage")
            //     {
            //         spin.Increment = 100;
            //     }
            //     else
            //     {
            //         spin.Increment = 2;
            //     }
            // }

            void gvCustomRowCellEditForEditing(object sender, CustomRowCellEditEventArgs e)
            {
                GridView gView = sender as GridView;
                ColumnView cView = sender as ColumnView;

                var formatType = (string)gView.GetListSourceRowCellValue(e.RowHandle, "format");
                var valueType = (string)gView.GetListSourceRowCellValue(e.RowHandle, "type");
                var name = (string)gView.GetListSourceRowCellValue(e.RowHandle, "name");

                spin.Mask.EditMask = default;
                if (e.Column.FieldName != "value") return;
                switch (formatType.ToLower())
                {
                    case "currency":
                        if (name.ToLower() == "treasury")
                        {
                            // spin.Mask.EditMask = "N";
                            spin.Increment = 1000000000000;   
                        } else spin.Increment = 2000;
                        break;
                    case "percentage":
                        spin.Mask.EditMask = "#############.0%";
                        spin.Increment = (decimal) float.Parse("0,1");
                        break;
                    default:
                        // spin.Increment = (decimal) float.Parse("0,1");
                        break;
                }

                if (formatType.Contains("volumes"))
                {
                    spin.Mask.EditMask = "####,###,###,###,###";
                    spin.Increment = 1000000;
                }
                switch (valueType)
                {
                    case "float":
                        spin.IsFloatValue = true;
                        break;
                    default:
                        spin.IsFloatValue = false;
                        break;
                }
                e.RepositoryItem = spin;
            }

            spin.Validating += (sender, args) =>
            {
                // gv.PostEditor();
            };
            spin.EditValueChanged += (object sender, EventArgs e) =>
            {
                gv.PostEditor();
            };



            gv.ValidatingEditor += (sender, args) =>
            {
                 GridView gView = sender as GridView;
                 if (gView.FocusedColumn == gView.Columns["value"]) {
                     var name = gView.GetRowCellValue(gView.FocusedRowHandle, "name");
                     rw.SRWrite(name.ToString(), args.Value.ToString());
                     gv.PostEditor();
                     // DateTime? orderDate = view.GetRowCellValue(view.FocusedRowHandle, colOrderDate) as DateTime?;
                     // if (requiredDate < orderDate) {
                     //     e.Valid = false;
                     //     e.ErrorText = "Required Date is earlier than the order date";
                     // }
                 }
            };
            gv.CustomRowCellEditForEditing += gvCustomRowCellEditForEditing;
        }

        private WorldUNOpinion ConvertWorldOpinion(float opinion)
        {
            if (opinion <= 0.10)
                return WorldUNOpinion.Outraged;
            else if (opinion < 0.30)
                return WorldUNOpinion.Dissaproving;
            else if (opinion < 0.40)
                return WorldUNOpinion.Concerned;
            else if (opinion < 0.50)
                return WorldUNOpinion.Indifferent;
            else if (opinion < 0.60)
                return WorldUNOpinion.Satisfied;
            else if (opinion < 0.70)
                return WorldUNOpinion.Pleased;
            else
                return opinion > 0.70 ? WorldUNOpinion.Delighted : WorldUNOpinion.Unknown;
        }

        private void gvCustomColumnDisplayText(object sender, CustomColumnDisplayTextEventArgs e)
        {
            ColumnView view = sender as ColumnView;
            CultureInfo ciUSA = new CultureInfo("en-US");
            // CultureInfo ciUSA = new Cul("en-US");
            // if (e.Column.FieldName != "value" || e.ListSourceRowIndex == GridControl.InvalidRowHandle) return;
            if (e.Column.FieldName != "value") return;
            var formatType = (string)view.GetListSourceRowCellValue(e.ListSourceRowIndex, "format");
            var type = (string)view.GetListSourceRowCellValue(e.ListSourceRowIndex, "type");
            var name = (string)view.GetListSourceRowCellValue(e.ListSourceRowIndex, "name");
            var value = (string)view.GetListSourceRowCellValue(e.ListSourceRowIndex, "value");
            // if (e.Column.Caption != "value") return;
            if (e.Value == null || e.Value == "") return;
            if (type == "string" || type == "byte") return;
            decimal formattedValue = Convert.ToDecimal(value == "" ? "0" : value);
            // var formattedValue = rw.SRRead(value, true);
            // var formattedValue = e.Value;
            switch (formatType)
            {
                case "opinion":
                    e.DisplayText = ConvertWorldOpinion((float) formattedValue).ToString();
                    break;
                case "currency":
                    // e.DisplayText = String.Format(ciUSA,"{0:C6}M", formattedValue);
                    e.DisplayText = String.Format(new MoneyFormat(), "{0:M}", formattedValue);
                    break;
                case "percentage":
                    e.DisplayText = String.Format("{0:P}", formattedValue);
                    break;
                case "volumes,Tonnes":
                    e.DisplayText = String.Format("{0:N} - Tonnes", formattedValue);
                    break;
                case "volumes,Barrels":
                    e.DisplayText = String.Format("{0:N} - Barrels", formattedValue);
                    break;
                case "volumes,kg":
                    e.DisplayText = String.Format("{0:N} - kg", formattedValue);
                    break;
                case "volumes,MWh":
                    e.DisplayText = String.Format("{0:N} - MWh", formattedValue);
                    break;
                case "volumes,m3":
                    e.DisplayText = String.Format("{0:N} - m3", formattedValue);
                    break;
            }
        }

        void updateSpinEdit(bool frz, SpinEdit ctrl)
        {
            if (frz)
                // ctrl.EditValue = rw.SRRead(ctrl.Tag.ToString());
                // rw.SRFreeze(ctrl.Tag.ToString(), ctrl.EditValue.ToString(), tglFreezeAllowIncrease.Checked);
                rw.SRWrite(ctrl.Tag.ToString(), ctrl.EditValue.ToString());
            else
                ctrl.EditValue = jsonReader.safeFeatureSearch(ctrl.Tag.ToString()).value;
            // ctrl.EditValue = rw.SRRead(ctrl.Tag.ToString());
        }
        void setContorlTag(CheckEdit ce, string tag)
        {
            var temp = new List<Feature>();
            
            // If CheckBox tag contains , split
            if (tag.Contains(","))
            {
                var split = tag.Split(',');
                
                // Add splitted varname in tag to Temp List
                foreach (var str in split)
                {
                    temp.Add(jsonReader.feature(str));
                }
                
                // Apply checkbox Tag with Temporary list
                // Add Event when checkstate is changed
                ce.Tag = temp;
                ce.CheckStateChanged += ceCheckStateChangedEvent;
            }
            else
            {
                // Else, contains only 1 varname param, then do the same.
                temp.Add(jsonReader.feature(tag));
                ce.Tag = temp;
                ce.CheckStateChanged += ceCheckStateChangedEvent;
            }
        }

        void setContorlTag(SpinEdit se, string tag)
        {
            se.Tag = tag;
        }

        // Set Spin Edit
        void setSpinEdit(SpinEdit[] se, IList<Feature> f)
        {
            // var ctg = f;

            foreach (var spin in se)
            {
                var ft = f.First(s => spin.Tag.ToString() == s.name);
                spin.EditValue = ft.value;
            }
            // f.Where( s => )
            // for (var i = 0; i < f.Count; i++)
            // {
            //     if (f[i].name == se[i].Tag)
            //     {
            //         se[i].EditValue = f[i].value;
            //     }
            // }
        }
        void UnitClassLookUpEditHandler(string featName, LookUpEdit le)
        {
            var dtsVal = le.Properties.GetDataSourceValue("Key", Int32.Parse(rw.SRRead(featName).ToString()));
            if (le.Focused)
            {
                if (le.EditValue != null && le.ItemIndex != null)
                {
                    // le.focu
                    rw.SRWrite(featName, le.ItemIndex.ToString(), "int");
                    // labelControl6.Text = le.EditValue.ToString();
                }
            }
            else
            {
                // Dillematic, supposed take from json which coupled, or just the varname but coupled to r/w
                if (jsonReader.feature(featName).value != null)
                {
                    le.EditValue = dtsVal;
                }
            }
        }
        
        // void leValidated(object sender, validated)
        void OnCustomColumnSort(object sender, CustomColumnSortEventArgs e)
        {
            // if (e.Column.FieldName == "displayName" || e.Column.FieldName == "display Name")
            // {
            //     int dayIndex1 = getIndexing((string)e.Value1);
            //     int dayIndex2 = 0;
            //     e.Result = dayIndex1.CompareTo(dayIndex2);
            //     e.Handled = true;
            // }
        }
        private void PopulateWarfareTypes(LookUpEdit leControl, Dictionary<int, string> dict)
        {
            // var a = new WarfareValueDictionary();
            leControl.Properties.DataSource = dict;
            leControl.Properties.DisplayMember = "Value";
            leControl.Properties.ValueMember = "Key";
            // leControl.EditValue = 0;
            leControl.ItemIndex = 0;
        }
        private void gvCountry_CustomColumnSort(object sender, DevExpress.XtraGrid.Views.Base.CustomColumnSortEventArgs e)
        {
            if (e.Column.FieldName == "displayName")
            {
                e.Handled = true;
            }
        }
        
        //When DAtasource changed by updatedaragridview()
        private void gvDataSourceChanged(object sender, EventArgs e)
        {
            GridView view = (GridView)sender;
            // gvHighlight();
            view.PostEditor();
            // view.refre
        }

        private void gvRowCellStyle(object sender, RowCellStyleEventArgs e)
        {
            GridView view = sender as GridView;
            var colName = e.Column.FieldName == "value";
            if (e.Column.FieldName == "value")
            {
                e.Appearance.BackColor = Color.Aqua;
            }
        }

        // Highlight GRIDVIEW when value increased
        private void gvHighlight(GridView gv)
        {
            GridFormatRule highlight(string ruleName,
                string iconName,
                string colorFill,
                FormatConditionDataUpdateTrigger trigger)
            {
                GridFormatRule gridFormatRule = new GridFormatRule();
                FormatConditionRuleDataUpdate dataUpdate = new FormatConditionRuleDataUpdate();

                gridFormatRule.Column = gv.Columns["value"];
                gridFormatRule.Name = ruleName;
                dataUpdate.HighlightTime = 500;
                dataUpdate.Icon.PredefinedName = iconName;
                dataUpdate.PredefinedName = colorFill;
                dataUpdate.Trigger = trigger;
                gridFormatRule.Rule = dataUpdate;
                gridFormatRule.ApplyToRow = true;
                return gridFormatRule;
            };
            // foreach (GridColumn gvColumn in gv.Columns)
            // {
            //     gridFormatRule.Column = gvColumn;
            // }
            // gridFormatRule.Column = "value";
            gv.FormatRules.Add(highlight("Format1", 
                "Flags3_1.png",
                "Green Fill",
                FormatConditionDataUpdateTrigger.ValueIncreased));
            gv.FormatRules.Add(highlight("Format2", 
                "Flags3_1.png",
                "Red Fill",
                FormatConditionDataUpdateTrigger.ValueDecreased));
        }

        private void gvShowingEditor(object sender, CancelEventArgs e)
        {
            GridView view = (GridView)sender;
            bool isEditable = (bool)view.GetRowCellValue(view.FocusedRowHandle, "editable");
            e.Cancel = !isEditable;
        }

        // When row validated write to MEM
        private void gvValidateRow(object sender, ValidateRowEventArgs e)
        {
            GridView view = (GridView)sender;
            var rowValue = view.GetRowCellValue(e.RowHandle, "value");
            var rowName = view.GetRowCellValue(e.RowHandle, "name");
            rw.SRWrite(rowName.ToString(), rowValue.ToString());
        }

        private void UpdateDataGridView(GridView gv,  IList<Feature> f)
        {
            if (!jsonReader.activeTrainer.GameValidated) return;
            
            for (int i = 0; i < f.Count; i++)
            {
                if (f[i].freeze)
                {
                    // DIRTY HACK
                    // if(f[i].name != "ArmyExperience") 
                    rw.SRFreeze(f[i].name, f[i].value, tglFreezeAllowIncrease.Checked);
                    f[i].value = rw.SRRead(f[i].name);
                }
                else
                {
                    // if(rw.SRRead(f[i].name).GetType().ToString() == "ïnt") 
                        // f[i].value = rw.SRRead(f[i].name).ToString();
                    // else
                    if (rw.SRRead(f[i].name).GetType().ToString() == "byte")
                        f[i].value = rw.SRRead(f[i].name);
                    else
                        f[i].value = rw.SRRead(f[i].name).ToString();
                    // gv.PostEditor();
                }
            }
            for (int j = 0; j < gv.DataRowCount; j++)
            {
                // var rowName = gv.GetRowCellValue(j, "name");
                // var rowGridId = gv.GetRowCellValue(j, "gridId");
                if(gv.GetRowCellValue(j, "gridId") != (object) j) 
                    gv.SetRowCellValue(j, gv.Columns["gridId"], j);
                gv.RefreshRowCell(j, gv.Columns["value"]);
                gv.RefreshRowCell(j, gv.Columns["original"]);
                gv.RefreshRowCell(j, gv.Columns["freeze"]);
                // var rNameValue = gv.GetDataRow(j)["name"];
                // var rValueValue = gv.GetDataRow(j)["value"];
                // var rFreeze = gv.GetDataRow(j)["freeze"];
                // if((bool)rFreeze)
                //     rw.SRFreeze(rNameValue.ToString(), rValueValue.ToString());
            }
            // gv.PostEditor();

            // gv.PostEditor();
            // gv.RefreshData();
        }
        private void UpdateUnitHistoryList(IList<Feature> currentUnitStats)
        {
            if (jsonReader.activeTrainer.GameValidated)
                UnitHistoryList.Instance.AddIfNotExists(currentUnitStats);
            var unitName = jsonReader.getUnitName(currentUnitStats);
            var ustats = UnitHistoryList.Instance.GetUnitOriginalValueByName(unitName);
            for (int i = 0; i < currentUnitStats.Count; i++)
            {
                if (ustats != null)
                {
                    var original = ustats[i].value;
                    if (original != null) currentUnitStats[i].original = original;
                }   
            }
        }

        // TODO: Refactor to be more simple and clean
        // private void calculateHealth()
        // {
        //     float currentHealth = rw.SRRead("ArmyCurrentStrength", true);
        //     float actualHealth = rw.SRRead("ArmyActualStrength", true);
        //     float suppliesCap = rw.SRRead("UnitSuppliesCapacity", true);
        //     float supplies = rw.SRRead("ArmySupply", true);
        //     float fuelCap = rw.SRRead("UnitFuelCapacity", true);
        //     float fuel = rw.SRRead("ArmyGas", true);
        //     // jsonReader.feature("ArmyCurrentStrength", jsonReader.FeaturesWarfare).value = currentHealth.ToString();
        //     // jsonReader.feature("ArmyActualStrength", jsonReader.FeaturesWarfare).value = actualHealth.ToString();
        //     // jsonReader.feature("UnitSuppliesCapacity", jsonReader.FeaturesWarfare).value = suppliesCap.ToString();
        //     // jsonReader.feature("UnitFuelCapacity", jsonReader.FeaturesWarfare).value = fuelCap.ToString();
        //     // jsonReader.feature("ArmySupply", jsonReader.FeaturesWarfare).value = supplies.ToString();
        //     // jsonReader.feature("ArmyGas", jsonReader.FeaturesWarfare).value = fuel.ToString();
        //     
        //     // Show Fuel CAP
        //     seUnitActualFuel.EditValue = (decimal)(currentHealth * fuelCap);
        //     // Show Supplies Cap
        //     seUnitActualSupplies.EditValue = (decimal)(currentHealth * suppliesCap);
        //
        //     // seUnitFuel.EditValue = fuelCap;
        //     // seUnitGas.EditValue = suppliesCap;
        //     // seUnitStrActual.EditValue = fuelCap;
        //     // seUnitFuel.EditValue = fuelCap;
        //     
        //     //!! Army Morale, Efficiency, Experience
        //     if (ceMorale.Checked)
        //         rw.SRFreeze("ArmyMorale", "5");
        //     if (ceExperience.Checked)
        //     {
        //         string rat = "0";
        //         switch (rtExperience.Rating)
        //         {
        //             case 1:
        //                 rat = "0.9";
        //                 break;
        //             case 2:
        //                 rat = "3";
        //                 break;
        //             case 3:
        //                 rat = "6";
        //                 break;
        //             default:
        //                 rat = "0";
        //                 break;
        //         }
        //         rw.SRWrite("ArmyExperience", rat);
        //     }
        //     if(ceEfficiency.Checked)
        //         rw.SRFreeze("ArmyEfficiency", "5");
        //     
        //     
        //
        //     // Heal
        //     if (checkedListBoxControl1.Items[WarfareArmyEnum.Heal].CheckState == CheckState.Checked)
        //     {
        //         if (actualHealth < currentHealth)
        //         {
        //             rw.SRWrite("ArmyCurrentStrength", (currentHealth).ToString());
        //             rw.SRWrite("ArmyGas", (fuelCap * currentHealth).ToString());
        //             rw.SRWrite("ArmySupply", (suppliesCap * currentHealth).ToString());
        //         }
        //         else
        //         {
        //             rw.SRWrite("ArmyCurrentStrength", (actualHealth).ToString());
        //             rw.SRWrite("ArmyGas", (fuelCap * actualHealth).ToString());
        //             rw.SRWrite("ArmySupply", (suppliesCap * actualHealth).ToString());
        //         }
        //     }
        //     
        //     // Naval Health
        //     if (rw.SRIsNaval(lookBoxUnitClass.ItemIndex))
        //     {
        //         if (!seNavalStrCurrent.Focused && checkedListBoxControl1.Items[WarfareArmyEnum.Current].CheckState == CheckState.Unchecked)
        //             seNavalStrCurrent.EditValue = currentHealth;
        //         if (!seNavalStrActual.Focused)
        //             seNavalStrActual.EditValue = actualHealth;
        //         // Able to Write to current health if CEBOX is checked
        //         if(checkedListBoxControl1.Items[WarfareArmyEnum.Current].CheckState == CheckState.Checked)
        //             rw.SRWrite("ArmyCurrentStrength", seNavalStrCurrent.EditValue.ToString());
        //         // Able to Write to Actual health if CEBOX is checked
        //         if(checkedListBoxControl1.Items[WarfareArmyEnum.Actual].CheckState == CheckState.Checked)
        //             rw.SRWrite("ArmyActualStrength", seNavalStrActual.EditValue.ToString());
        //     }
        //     else
        //     {
        //         if (!seUnitStrCurrent.Focused)
        //             seUnitStrCurrent.Value = (decimal)currentHealth;
        //         if (!seUnitStrActual.Focused && !ceUnitStrength.Checked)
        //             seUnitStrActual.Value = (decimal)actualHealth;
        //         if(checkedListBoxControl1.Items[WarfareArmyEnum.Current].CheckState == CheckState.Checked)
        //             rw.SRWrite("ArmyCurrentStrength", seUnitStrCurrent.EditValue.ToString());
        //         if(checkedListBoxControl1.Items[WarfareArmyEnum.Actual].CheckState == CheckState.Checked)
        //             rw.SRWrite("ArmyActualStrength", seUnitStrActual.EditValue.ToString());
        //     }
        //
        //     // Gas Supply
        //     if (!seUnitFuel.Focused && !ceUnitSupplies.Checked)
        //         seUnitFuel.EditValue = (decimal)rw.SRRead("ArmyGas", true);
        //     if (!seUnitSupplies.Focused && !ceUnitSupplies.Checked)
        //         seUnitSupplies.EditValue = (decimal)rw.SRRead("ArmySupply", true);
        // }

        private void UnitReader(SpinEdit se, IList<Feature> fts)
        {
            // string armyHealth;
            // string armyMaxHealth;
            se.EditValue = jsonReader.feature(se.Tag.ToString(), fts).value;
            // if (se.Focused)
            // {
            //     
            // }
            // foreach (var ft in fts)
            // {
            //     if (ft == null) return;
            //     if (ft.name == seStaffActive.Tag.ToString())
            //         seStaffActive.EditValue = ft.value;
            //     if (ft.name == seStaffReserve.Tag.ToString())
            //         seStaffReserve.EditValue = ft.value;
            //     
            //     if (ft.name == seUnitStrActual.Tag.ToString())
            //         if (float.Parse(ft.value) <= 1)
            //             seNavalStrActual.EditValue = ft.value;
            //         else
            //             seUnitStrActual.EditValue = ft.value;
            //     
            //     if (ft.name == seUnitStrCurrent.Tag.ToString())
            //         if (float.Parse(ft.value) <= 1)
            //             seNavalStrCurrent.EditValue = ft.value;
            //         else
            //             seUnitStrCurrent.EditValue = ft.value;
            //     
            //     if (ft.name == seUnitFuel.Tag.ToString())
            //         seUnitFuel.EditValue = ft.value;
            //     if (ft.name == seUnitGas.Tag.ToString())
            //         seUnitGas.EditValue = ft.value;
            // }
            // seUnitStrActual = ;
            // seUnitStrCurrent = "";
            // seNavalStrActual = "";
            // seNavalStrCurrent = "";
            // seUnitFuel = "";
            // seUnitGas = "";
            // ceMorale = ""
        }

        private void MissileMadness()
        {
            if (ceMissiles.Checked && Convert.ToInt32(seMissiles.EditValue) >= 0)
            {
                var intMissile = Convert.ToInt32(seMissiles.EditValue);
                if (intMissile < int.MaxValue)
                {
                    var missileValue = intMissile.ToString();
                    rw.SRWrite("ArmyMissileAvailableStorageQuantity", missileValue);
                    rw.SRWrite("ArmyMissileAvailableCargoQuantity", missileValue);
                    rw.SRWrite("ArmyMissileStrategicPoolAssigned", missileValue);
                    rw.SRWrite("ArmyMissileStrategicPoolReserve", missileValue);
                }
            }
        }

        private void SpecialOption()
        {
            if (cbADayBuild.Checked)
                rw.SRWrite("ADayBuild", 
                    rw.SRRead("ADayBuild", true) >= 1 ? "1" : "0.999");
            if (cbADayArmy.Checked)
                rw.SRWrite("ADayArmy", "0.001");
            if (cbADayResearch.Checked)
            {
                rw.SRWrite("ADayResearchClick", "0.001");
                rw.SRWrite("ADayResearchTooltip", "0.001");
            }
            
            if (ceSatComm.Checked)
                rw.SRWrite("SatelliteCommCoverage", "1");
            if (ceSatMilDef.Checked)
                rw.SRWrite("SatelliteMissileDefenseCoverage", "1"); 
            if (ceSatRecon.Checked)
                rw.SRWrite("SatelliteReconCoverage", "1");
            
            switch (rgResearchEfficiency.SelectedIndex)
            {
                case 0:
                    break;
                case 1:
                    rw.SRWrite("ResearchEfficiency", "2");
                    break;
                case 2:
                    rw.SRWrite("ResearchEfficiency", "4");
                    break;
                case 3:
                    rw.SRWrite("ResearchEfficiency", "8");
                    break;
                case 4:
                    rw.SRWrite("ResearchEfficiency", "100");
                    break;
                default:
                    break;
            }
        }
        private void timer1_Tick_1(object sender, EventArgs e)
        {
            // string unitName = rw.SRRead("UnitName");
            // string unitID = rw.SRRead("UnitID");
            string unitSelected = jsonReader.feature("UnitSelected", jsonReader.FeaturesWarfare).value;
            string unitDeployed = jsonReader.feature("UnitDeployed", jsonReader.FeaturesWarfare).value;
            string unitReserved = jsonReader.feature("UnitReserve", jsonReader.FeaturesWarfare).value;
            string unitBattleGroup = jsonReader.feature("UnitBattleGroup", jsonReader.FeaturesWarfare).value;
            int unitPDeployed = (unitDeployed.StrToInt());
            int unitPReserved = unitReserved.StrToInt();
            int unitTotal = unitPDeployed + unitPReserved;

            memoEdit1.EditValue = $@"Selected: {unitSelected}
Deployed: {unitDeployed} ({NumericExtension.SafePercentage(unitPDeployed, unitTotal)})
Reserved: {unitReserved} ({NumericExtension.SafePercentage(unitPReserved, unitTotal)})
Battle Group: {unitBattleGroup}";

            SpecialOption();
            MissileMadness();
            // countryInfoTable.UpdateTable();
            UpdateDataGridView(gvResources, jsonReader.FeaturesResources);
            UpdateDataGridView(gvCountry,jsonReader.FeaturesCountry);
            UpdateDataGridView(gvWarfare, jsonReader.FeaturesWarfare);
            UpdateUnitHistoryList(jsonReader.FeaturesWarfare);
            _isNaval = rw.SRIsNaval(Convert.ToInt32(UnitClass.value));
            
            // UpdateUnitHistoryList(gvUnitHistoryList);
            // gvUnitHistoryList.DataSource = UnitHistoryList.Instance.unitIdList;
            // gvUnitHistory.DataSource = gcUnitHistoryList
            // So pointer will fetch after updated data grid
            
            // updateSpinEdit(ceUnitStrength.Checked, seUnitStrActual);
            
            // update Spinedit EDIT VALUE
            // updateSpinEdit(ceUnitStrength.Checked, seUnitStrCurrent);
            // updateSpinEdit(ceUnitFuel.Checked, seUnitFuel);
            // updateSpinEdit(ceUnitSupplies.Checked, seUnitSupplies);

            // Unit Movement/target/class Refresh every tick
            
            // ARMY - Class updater and changer. 
            UnitClassLookUpEditHandler("UnitMovementType",lookBoxUnitMovementType);
            UnitClassLookUpEditHandler("UnitTargetType",lookBoxUnitTargetType);
            UnitClassLookUpEditHandler("UnitClass",lookBoxUnitClass);
            
            
            // Reader unified
            ArmyControlReader();
            ArmyControlWriter();
            
            // Set specific spinedit to display % when naval is selected
            SetSpinEditDisplayPercentage(seUnitStrActual, _isNaval);
            SetSpinEditDisplayPercentage(seUnitStrCurrent, _isNaval);
            
            // READ ARMY ACTIVE STAFF REES
            // UnitReader(seStaffActive, jsonReader.FeaturesWarfare);
            // UnitReader(seStaffReserve, jsonReader.FeaturesWarfare);
            // UnitReader(seUnitFuel, jsonReader.FeaturesWarfare);
            // UnitReader(seUnitGas, jsonReader.FeaturesWarfare);
            
            // This update Army Naval Health blablabla
            // calculateHealth();
            
            // Multiplayer Protection
            MultiplayerProtection();
        }

        public void MultiplayerProtection()
        {
            if (rw.SRRead("MultiplayerReadyState", true, jsonReader.FeaturesSpecial) != 1) return;
            mainTimer.Enabled = false;
            XtraMessageBox.Show("No Multiplayer! sorry :(");
            Application.Exit();
        }
        public void ArmyControlReader()
        {
            // seStaffActive.ismo

            Int64 converter(string val)
            {
                return Convert.ToInt64(decimal.Parse(val));
            }

            // Active Staff
            seStaffActive.EditValue = ArmyActiveStaff.value;
            if(!seStaffReserve.IsEditorActive)
                seStaffReserve.EditValue = ArmyReserve.value;

            if (!seUnitStrCurrent.IsEditorActive && !ceUnitStrength.Checked)
                seUnitStrCurrent.EditValue = converter(ArmyCurrentStrength.value);
            if(!seUnitStrActual.IsEditorActive) 
                seUnitStrActual.EditValue = converter(ArmyActualStrength.value);
            // }
           
            // Fuel Editor
            if(!seUnitFuel.IsEditorActive && !ceUnitFuel.Checked)
                seUnitFuel.EditValue = converter(ArmyGas.value);
            seUnitActualFuel.EditValue = (int)(decimal.Parse(ArmyCurrentStrength.value) * decimal.Parse(UnitFuelCapacity.value));
            
            // Supplies Editor
            if(!seUnitSupplies.IsEditorActive && !ceUnitFuel.Checked) 
                seUnitSupplies.EditValue = converter(ArmySupply.value); 
            seUnitActualSupplies.EditValue = (int)(decimal.Parse(ArmyCurrentStrength.value) * decimal.Parse(UnitSuppliesCapacity.value));

            // Health Bars
            showHealthBar();
            
            // Morale Bars
            showBar(pbArmyMoraleBar, ArmyMorale, 100);

            // Efficiency Bar
            showBar(pbArmyEfficiencyBar, ArmyEfficiency, 120);

            // Experience Stars
            showExperienceStar(ArmyEfficiency);
        }

        private void showExperienceStar(Feature armyexp)
        {
            if (ceExperience.Checked) return;
            if (armyexp.value.StrToDouble() < 0.25)
                rtExperience.Rating = 0;
            if (ArmyExperience.value.StrToDouble().IsBetween(0.25, 1))
                rtExperience.Rating = 1;
            if (ArmyExperience.value.StrToDouble().IsBetween(1, 2.25))
                rtExperience.Rating = 2;
            if (ArmyExperience.value.StrToDouble().IsBetween(2.24, 99999))
                rtExperience.Rating = 3;
        }

        private void ArmyControlWriter()
        {
            if (ceMorale.Checked)
                gvWarfare.gvSetRowCellValue("value", "ArmyMorale", "10", true);
            // rw.SRWrite("ArmyMorale", "10.0");
            if(ceExperience.Checked)
                gvWarfare.gvSetRowCellValue("value", "ArmyExperience", "10", true);
            // rw.SRWrite("ArmyExperience", "10.0");
            if(ceEfficiency.Checked)
                gvWarfare.gvSetRowCellValue("value", "ArmyEfficiency", "10", true);
            // rw.SRWrite("ArmyEfficiency", "10.0");

            bool IsChecked(WarfareArmyEnum e)
            {
                return checkedListBoxControl1.Items[e].CheckState == CheckState.Checked;
            }
            
            // Init For special 
            var actualStrength = ArmyActualStrength.value.StrToDecimal();
            var actualGas = (ArmyCurrentStrength.value.StrToDecimal() * UnitFuelCapacity.value.StrToDecimal());
            var actualSupply = (ArmyCurrentStrength.value.StrToDecimal() * UnitSuppliesCapacity.value.StrToDecimal());

            
            // Multiplier
            var supplyGasMultiplier = 1;
            var strMultiplier = 1;
            
            
            // Heal
            if (IsChecked(WarfareArmyEnum.Heal))
            {
                if (ArmyCurrentStrength.value.StrToDecimal() < ArmyActualStrength.value.StrToDecimal())
                    rw.SRWrite(ArmyCurrentStrength.name, (ArmyActualStrength.value.StrToInt()).ToString());
                if (ArmyGas.value.StrToDecimal() < actualGas)
                    rw.SRWrite(ArmyGas.name,actualGas.ToString());
                if (ArmySupply.value.StrToDecimal() < actualSupply) 
                    rw.SRWrite(ArmySupply.name, actualSupply.ToString());
            }
            
            // Rambo
            if (IsChecked(WarfareArmyEnum.Rambo))
            {
                // ceEfficiency.Checked = true;
                // ceExperience.Checked = true;
                // ceMorale.Checked = true;
                // if (!IsChecked(WarfareArmyEnum.Rambo))
                // {
                //     ceEfficiency.Checked = false;     
                //     ceExperience.Checked = false;
                //     ceMorale.Checked = false;
                // }
            }

            // 2x Str
            if (IsChecked(WarfareArmyEnum.Str2x))
            {
                strMultiplier = strMultiplier + 2;
                rw.SRWrite(ArmyCurrentStrength.name, (actualStrength * strMultiplier).ToString());
            }
            
            // 4x Str
            if (IsChecked(WarfareArmyEnum.Str4x))
            {
                strMultiplier = strMultiplier + 4;
                rw.SRWrite(ArmyCurrentStrength.name, (actualStrength * strMultiplier).ToString());
            }
            
            // 2x SupplyGas
            if (IsChecked(WarfareArmyEnum.GasSupply2x))
            {
                supplyGasMultiplier = supplyGasMultiplier + 2;
                rw.SRWrite(ArmyGas.name, (actualGas * supplyGasMultiplier).ToString("N"));
                rw.SRWrite(ArmySupply.name, (actualSupply * supplyGasMultiplier).ToString("N"));
                
            }
            
            // 4x SupplyGas
            if (IsChecked(WarfareArmyEnum.GasSupply4x))
            {
                supplyGasMultiplier = supplyGasMultiplier + 4;
                rw.SRWrite(ArmyGas.name, (actualGas * supplyGasMultiplier).ToString("N"));
                rw.SRWrite(ArmySupply.name, (actualSupply * supplyGasMultiplier).ToString("N"));
            }
        }

        private void showBar(ProgressBarControl pbc, Feature source, int MaxValue)
        {
            int realVal = (int) (Convert.ToDecimal(source.value) * 100);
            if (realVal >= MaxValue) realVal = MaxValue;
            pbc.Position = realVal;
            pbc.Properties.Maximum = MaxValue;
        }

        // Bar Override Deactivate
        protected void FormDeactivate(object sender, EventArgs e)
        {
            if (bar2.IsFloating)//your condition  
                {
                    ISupportWindowActivate act = bar2 as ISupportWindowActivate;
                    if (act != null) act.Activate();
                }
        }
        private void bar2_DockChanged(object sender, EventArgs e)
        {
            // if (bar2.IsFloating)
            // {
            //     this.TopMost = barTglOnTop.Checked;
            // }
            // else
            // {
            //     this.TopMost = barTglOnTop.Checked;
            // }
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            gcUnitHistoryList.DataSource = UnitHistoryList.Instance.UnitList;
        }

        private void setSpinEditorEvent(SpinEdit se)
        {
            se.Properties.ValidateOnEnterKey = true;
            se.Validating += spinValidatingEvent;
            se.MouseEnter += (sender, args) =>
            {
                // se.Focus();
            };
            se.LostFocus += (sender, args) =>
            {
                // SpinEdit se = sender as SpinEdit;
            };
            se.Spin += setSpinEvent;
        }

        private void spinValidatingEvent(object sender, CancelEventArgs e)
        {
            SpinEdit se = (SpinEdit) sender;
            rw.SRWrite(se.Tag.ToString(), se.EditValue.ToString());
        }
        
        private void setSpinEvent(object sender, SpinEventArgs e)
        {
            SpinEdit se = (SpinEdit) sender;
            // Feature v = jsonReader.safeFeatureSearch(se.Tag.ToString(), warfareList);
            // se.EditValue = v.value;
            // // MessageBox.Show($"SE VALUE {se.Value}");
            // // MessageBox.Show($"v VALUE {v.value}");
            // // MessageBox.Show($"se EDIT VALUE {se.EditValue}");
            // v.value = se.EditValue.ToString();
            se.Properties.BeginUpdate();
            rw.SRWrite(se.Tag.ToString(), se.EditValue.ToString());
            se.Properties.EndUpdate();
        }
        private void seModifiedEvent(object sender, EventArgs e)
        {
            SpinEdit se = (SpinEdit) sender;
            rw.SRWrite(se.Tag.ToString(), se.EditValue.ToString());
            //if (se.Tag.ToString)
            //}
        }
        private void ceCheckStateChangedEvent(object sender, EventArgs e) {
            CheckEdit ce = sender as CheckEdit;
            
            List<Feature> tags = ce.Tag.CastTo<List<Feature>>();
            for (int i = 0; i < tags.Count; i++)
            {
                if (ce.Checked && tags[i].freeze) continue;
                tags[i].freeze = ce.Checked;
                // if (tags[i].category == "Warfare")
                    // gvWarfare.SetRowCellValue(tags[i].gridId, "freeze", ce.Checked);
                    // var gvFreeze = gvWarfare.GetRowCellValue(tags[i].gridId, "freeze");
                    // rw.SRWrite(tags[i].name, tags[i].value);
                // rw.SRFreeze(tags[i].name, tags[i].value);
            }
        }
        private void barBtBestFitColumn_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            gvCountry.BestFitColumns();
            gvWarfare.BestFitColumns();
            gvResources.BestFitColumns();
        }

        private void xtraTabControl1_Selected(object sender, DevExpress.XtraTab.TabPageEventArgs e)
        {
            gvCountry.BestFitColumns();
            gvWarfare.BestFitColumns();
            gvResources.BestFitColumns();
        }

        private void barEditItem3_EditValueChanged(object sender, EventArgs e)
        {
          
            // TrackBarControl trackBar = sender as TrackBarControl;
            if (barEditItem3.EditValue != null)
            {
                var val = Convert.ToInt32(barEditItem3.EditValue);
                this.Opacity = (double) val / 100;
            }
        }

        private void barTglOnTop_CheckedChanged(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            TopMost = barTglOnTop.Checked;
            Properties.Settings.Default.UserAlwaysOnTop = barTglOnTop.Checked;
        }

        private void skinDropDownButtonItem1_DownChanged(object sender, ItemClickEventArgs e)
        {
            SkinDropDownButtonItem skin = sender as SkinDropDownButtonItem;
            Properties.Settings.Default.UserThemes = LookAndFeel.ActiveSkinName;
        }

        private void barButtonItem2_ItemClick(object sender, ItemClickEventArgs e)
        {
            // _form1 = new Form1();
            // _form1.Show();
        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {
            rw.SRFreezePersistent("ArmyMorale", true, "0,1");
        }

        private void barButtonItem3_ItemClick(object sender, ItemClickEventArgs e)
        {
            System.Windows.Forms.Application.Exit();
        }

        private void memoEdit2_EditValueChanged(object sender, EventArgs e)
        {

        }

        private void barBtnDonationBottom_ItemClick(object sender, ItemClickEventArgs e)
        {

        }
    }
}