package main

type AutoGenerated struct {
	SRFAuthor      string   `json:"SRFAuthor"`
	SRFEmail       string   `json:"SRFEmail"`
	SRFTwitter     string   `json:"SRFTwitter"`
	SRFWebsite     string   `json:"SRFWebsite"`
	SRFName        string   `json:"SRFName"`
	SRFDescription string   `json:"SRFDescription"`
	SRFIdentifier  string   `json:"SRFIdentifier"`
	SRFVersion     string   `json:"SRFVersion"`
	SRFTags        []string `json:"SRFTags"`
	SRFSchema      string   `json:"SRFSchema"`
	Games          []Games  `json:"Games"`
}
type Pointers struct {
	ID            int           `json:"id"`
	Name          string        `json:"name"`
	Description   string        `json:"description"`
	Category      string        `json:"category"`
	CategoryScope []interface{} `json:"categoryScope"`
	OffsetsList   []int         `json:"offsetsList"`
	Pointer       string        `json:"pointer"`
}
type Features struct {
	ID             int    `json:"id"`
	PointerID      int    `json:"pointerId"`
	Name           string `json:"name"`
	DisplayName    string `json:"displayName"`
	Type           string `json:"type"`
	Category       string `json:"category"`
	Description    string `json:"description"`
	Value          string `json:"value"`
	FormattedValue string `json:"formattedValue"`
	Format         string `json:"format"`
	Offset         string `json:"offset"`
	Editable       bool   `json:"editable"`
	Enabled        bool   `json:"enabled"`
}
type Categories struct {
	ID                int        `json:"id"`
	FeatureCount      int        `json:"featureCount"`
	Category          string     `json:"category"`
	Description       string     `json:"description"`
	ColumnsVisibility []int      `json:"columnsVisibility"`
	Features          []Features `json:"features"`
}
type Versions struct {
	GameVersion  string       `json:"GameVersion"`
	Availability bool         `json:"Availability"`
	Pointers     []Pointers   `json:"Pointers"`
	Categories   []Categories `json:"Categories"`
}
type Games struct {
	DisplayName string     `json:"DisplayName"`
	ProcessName string     `json:"ProcessName"`
	Versions    []Versions `json:"Versions"`
}