using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SRUL.Types
{
    class TechEffects
    {
        public static Dictionary<int, string> TechNames = new Dictionary<int, string>
        {
            {2, "Industrialization"}
        };

        public static Dictionary<string, int> TechDictionarySource = new Dictionary<string, int>
        {
            {"1: (Not used?)", 1},
            {"2: Finished Goods Facilities Cost", 2},
            {"3: Facilities Construction Materials Use", 3},
            {"4: Pollution Levels (Not used)", 4},
            {"5: Research Efficiency", 5},
            {"6: Counter Intelligence Efficiency", 6},
            {"7: Intelligence Efficiency", 7},
            {"8: Military Efficiency", 8},
            {"9: City Power Generation", 9},
            {"10: Mine Field Damage on us (Not used)", 10},
            {"11: Mine Field Lethality (Not used)", 11},
            {"12: Chemical Weapon Protection (Unused prior to SRGW / SRU 9.1.26)", 12},
            {"13: Vehicle Fuel Consumption", 13},
            {"14: Cost of Motorized Units", 14},
            {"15: Unit Build Speed", 15},
            {"16: Facility Build Speed", 16},
            {"17: Urban Development (no longer used; now uses replaceby and Tech PreReq's in Equip List)", 17},
            {"18: Finished Goods Facilities Efficiency", 18},
            {"19: Finished Goods Costs", 19},
            {"20: Transportation Improvement (Not used)", 20},
            {"21: Space Race", 21},
            {"22: Nuclear Plant Maintenance Cost", 22},
            {"23: GUI Skin (Special case, selects GUI Skin)", 23},
            {"24: Finished Goods Agri Raw Use", 24},
            {"25: Finished Goods Rubber Raw Use (was Water pre-SR1936)", 25},
            {"26: Finish Goods Timber Raw Use", 26},
            {"27: Finished Goods Petrol Raw Use", 27},
            {"28: Finished Goods Coal Raw Use", 28},
            {"29: Finished Goods Ore Raw Use", 29},
            {"30: Finish Goods Uranium Raw Use", 30},
            {"31: Finished Goods Electrical Raw Use", 31},
            {"32: Finish Goods Consumer Raw Use", 32},
            {"33: Finished Goods Industrial Raw Use", 33},
            {"34: Finish Goods Military Raw Use", 34},
            {"35: Synthetic Rubber Production", 35},
            {"36: Hydroponic Plant Production", 36},
            {"37: Composites Plant Production", 37},
            {"38: SynthFuel Plant Production", 38},
            {"39: Power - Coal Production", 39},
            {"40: Power - Nuclear Production", 40},
            {"41: Power - Petrol Production", 41},
            {"42: Power - Other Production", 42},
            {"43: Power - Fusion Production", 43},
            {"44: Consumer Goods Plant Production", 44},
            {"45: Industrial Goods Plant Production", 45},
            {"46: Military Goods Plant production", 46},
            {"47: Power - Antimatter Production", 47},
            {"48: Power - Dark Energy Production", 48},
            {"49: N/A", 49},
            {"50: N/A", 50},
            {"51: N/A", 51},
            {"52: N/A", 52},
            {"53: N/A", 53},
            {"54: N/A", 54},
            {"55: Oil Derrick Production", 55},
            {"56: Atomic Race", 56},
            {"57: Reserved", 57},
            {"58: Internet Race", 58},
            {"59: Mars Race", 59},
            {"60: Population Agri Use", 60},
            {"61: Population Rubber Use (was Water pre-SR1936)", 61},
            {"62: Population Timber Use", 62},
            {"63: Population Petrol Use", 63},
            {"64: Population Coal Use", 64},
            {"65: Population Ore Use", 65},
            {"66: Population Uranium Use", 66},
            {"67: Population Power Use", 67},
            {"68: Population Consumer Goods Use", 68},
            {"69: Population Ind Goods Use", 69},
            {"70: Population Mil Goods Use", 70},
            {"71: (Reserved)", 71},
            {"72: Output of Agriculture", 72},
            {"73: Output of Rubber (was Water pre-SR1936)", 73},
            {"74: Output of Timber", 74},
            {"75: Output of Petrol", 75},
            {"76: Output of Coal", 76},
            {"77: Output of Ore", 77},
            {"78: Output of Uranium", 78},
            {"79: Output of (All) Power", 79},
            {"80: Output of Consumer Goods", 80},
            {"81: Output of Industrial Goods", 81},
            {"82: Output of Military Goods", 82},
            {"83: (Reserved)", 83},
            {"84: Efficiency of Agriculture", 84},
            {"85: Efficiency of Rubber (was Water pre-SR1936)", 85},
            {"86: Efficiency of Timber", 86},
            {"87: Efficiency of Petrol", 87},
            {"88: Efficiency of Coal", 88},
            {"89: Efficiency of Ore", 89},
            {"90: Efficiency of Uranium", 90},
            {"91: Efficiency of Power", 91},
            {"92: Efficiency of Consumer Goods", 92},
            {"93: Efficiency of Industrial Goods", 93},
            {"94: Efficiency of Military Goods", 94},
            {"95: (Reserved)", 95},
            {"96: Garrison Infantry Level (New SRGW/SRU)", 96},
            {"97:", 97},
            {"98:", 98},
            {"99:", 99},
            {"100: Health Care Rating", 100},
            {"101: Education Rating", 101},
            {"102: Infrastructure Rating", 102},
            {"103: Environment Rating", 103},
            {"104: Family Rating", 104},
            {"105: Law Enforcement Rating", 105},
            {"106: Cultural Rating", 106},
            {"107: Social Services Rating", 107},
            {"108: Health Care Cost", 108},
            {"109: Education cost", 109},
            {"110: Infrastructure Cost", 110},
            {"111: Environment Cost", 111},
            {"112: Family Subsidy Cost", 112},
            {"113: Law Enforcement Cost", 113},
            {"114: Cultural Cost", 114},
            {"115: Social Services Cost", 115},
            {"116: Hard Target Defense", 116},
            {"117: Soft Target Defense", 117},
            {"118: Ground Attack Values", 118},
            {"119: Anti-Air Attack Values", 119},
            {"120: Anti-Ship Attack Values", 120},
            {"121: Anti-Sub Attack Values", 121},
            {"122: Ballistic Artillery Range", 122},
            {"123: Missile Accuracy", 123},
            {"124: Stealth Strength Values", 124},
            {"125: Spotting Strength Values", 125},
            {"126: MLRS Range", 126},
            {"127: Facility (Fortification) Defense", 127},
        };
        public static string[] TechEffectList = {
            "1: (Not used?)",
            "2: Finished Goods Facilities Cost",
            "3: Facilities Construction Materials Use",
            "4: Pollution Levels (Not used)",
            "5: Research Efficiency",
            "6: Counter Intelligence Efficiency",
            "7: Intelligence Efficiency",
            "8: Military Efficiency",
            "9: City Power Generation",
            "10: Mine Field Damage on us (Not used)",
            "11: Mine Field Lethality (Not used)",
            "12: Chemical Weapon Protection <i>(Unused prior to SRGW / SRU 9.1.26)</i>",
            "13: Vehicle Fuel Consumption",
            "14: Cost of Motorized Units",
            "15: Unit Build Speed",
            "16: Facility Build Speed",
            "17: Urban Development (no longer used; now uses <i>replaceby</i> and Tech PreReq's in Equip List)",
            "18: Finished Goods Facilities Efficiency",
            "19: Finished Goods Costs",
            "20: Transportation Improvement (Not used)",
            "21: Space Race",
            "22: Nuclear Plant Maintenance Cost",
            "23: GUI Skin (Special case, selects GUI Skin)",
            "24: Finished Goods Agri Raw Use",
            "25: Finished Goods Rubber Raw Use <i>(was Water pre-SR1936)</i>",
            "26: Finish Goods Timber Raw Use",
            "27: Finished Goods Petrol Raw Use",
            "28: Finished Goods Coal Raw Use",
            "29: Finished Goods Ore Raw Use",
            "30: Finish Goods Uranium Raw Use",
            "31: Finished Goods Electrical Raw Use",
            "32: Finish Goods Consumer Raw Use",
            "33: Finished Goods Industrial Raw Use",
            "34: Finish Goods Military Raw Use</li></ul>",
            "35: Synthetic Rubber Production",
            "36: Hydroponic Plant Production",
            "37: Composites Plant Production",
            "38: SynthFuel Plant Production",
            "39: Power - Coal Production",
            "40: Power - Nuclear Production",
            "41: Power - Petrol Production",
            "42: Power - Other Production",
            "43: Power - Fusion Production",
            "44: Consumer Goods Plant Production",
            "45: Industrial Goods Plant Production",
            "46: Military Goods Plant production",
            "47: Power - Antimatter Production",
            "48: Power - Dark Energy Production",
            "49: N/A",
            "50: N/A",
            "51: N/A",
            "52: N/A",
            "53: N/A",
            "54: N/A",
            "55: Oil Derrick Production</li></ul>",
            "56: Atomic Race",
            "57: Reserved",
            "58: Internet Race",
            "59: Mars Race",
            "60: Population Agri Use",
            "61: Population Rubber Use <i>(was Water pre-SR1936)</i>",
            "62: Population Timber Use",
            "63: Population Petrol Use",
            "64: Population Coal Use",
            "65: Population Ore Use",
            "66: Population Uranium Use",
            "67: Population Power Use",
            "68: Population Consumer Goods Use",
            "69: Population Ind Goods Use",
            "70: Population Mil Goods Use",
            "71: (Reserved)</li></ul>",
            "72: Output of Agriculture",
            "73: Output of Rubber <i>(was Water pre-SR1936)</i>",
            "74: Output of Timber",
            "75: Output of Petrol",
            "76: Output of Coal",
            "77: Output of Ore",
            "78: Output of Uranium",
            "79: Output of (All) Power",
            "80: Output of Consumer Goods",
            "81: Output of Industrial Goods",
            "82: Output of Military Goods",
            "83: (Reserved)</li></ul>",
            "84: Efficiency of Agriculture",
            "85: Efficiency of Rubber <i>(was Water pre-SR1936)</i>",
            "86: Efficiency of Timber",
            "87: Efficiency of Petrol",
            "88: Efficiency of Coal",
            "89: Efficiency of Ore",
            "90: Efficiency of Uranium",
            "91: Efficiency of Power",
            "92: Efficiency of Consumer Goods",
            "93: Efficiency of Industrial Goods",
            "94: Efficiency of Military Goods",
            "95: (Reserved)</li></ul>",
            "96: Garrison Infantry Level (New SRGW/SRU)",
            "97:",
            "98:",
            "99:",
            "100: Health Care Rating",
            "101: Education Rating",
            "102: Infrastructure Rating",
            "103: Environment Rating",
            "104: Family Rating",
            "105: Law Enforcement Rating",
            "106: Cultural Rating",
            "107: Social Services Rating</li></ul>",
            "108: Health Care Cost",
            "109: Education cost",
            "110: Infrastructure Cost",
            "111: Environment Cost",
            "112: Family Subsidy Cost",
            "113: Law Enforcement Cost",
            "114: Cultural Cost",
            "115: Social Services Cost</li></ul>",
            "116: Hard Target Defense",
            "117: Soft Target Defense",
            "118: Ground Attack Values",
            "119: Anti-Air Attack Values",
            "120: Anti-Ship Attack Values",
            "121: Anti-Sub Attack Values",
            "122: Ballistic Artillery Range",
            "123: Missile Accuracy",
            "124: Stealth Strength Values",
            "125: Spotting Strength Values",
            "126: MLRS Range",
            "127: Facility (Fortification) Defense"
            };
    }
}
