//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor v
//     Source:                    https://github.com/msawczyn/EFDesigner
//     Visual Studio Marketplace: https://marketplace.visualstudio.com/items?itemName=michaelsawczyn.EFDesigner
//     Documentation:             https://msawczyn.github.io/EFDesigner/
//     License (MIT):             https://github.com/msawczyn/EFDesigner/blob/master/LICENSE
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data.Entity.Infrastructure.Annotations;

namespace SRUL
{
   /// <inheritdoc/>
   public partial class EFModel1 : DbContext
   {
      #region DbSets
      public virtual System.Data.Entity.DbSet<global::SRUL.CountryInformation> CountryInformations { get; set; }
      public virtual System.Data.Entity.DbSet<global::SRUL.Games> Games { get; set; }
      public virtual System.Data.Entity.DbSet<global::SRUL.Offset> Offsets { get; set; }
      public virtual System.Data.Entity.DbSet<global::SRUL.Pointers> Pointers { get; set; }
      public virtual System.Data.Entity.DbSet<global::SRUL.UnitInformation> UnitInformations { get; set; }
      public virtual System.Data.Entity.DbSet<global::SRUL.Versions> Versions { get; set; }
      #endregion DbSets

      #region Constructors

      partial void CustomInit();

      #warning Default constructor not generated for EFModel1 since no default connection string was specified in the model

      /// <inheritdoc />
      public EFModel1(string connectionString) : base(connectionString)
      {
         Configuration.LazyLoadingEnabled = true;
         Configuration.ProxyCreationEnabled = true;
         System.Data.Entity.Database.SetInitializer<EFModel1>(new EFModel1DatabaseInitializer());
         CustomInit();
      }

      /// <inheritdoc />
      public EFModel1(string connectionString, System.Data.Entity.Infrastructure.DbCompiledModel model) : base(connectionString, model)
      {
         Configuration.LazyLoadingEnabled = true;
         Configuration.ProxyCreationEnabled = true;
         System.Data.Entity.Database.SetInitializer<EFModel1>(new EFModel1DatabaseInitializer());
         CustomInit();
      }

      /// <inheritdoc />
      public EFModel1(System.Data.Common.DbConnection existingConnection, bool contextOwnsConnection) : base(existingConnection, contextOwnsConnection)
      {
         Configuration.LazyLoadingEnabled = true;
         Configuration.ProxyCreationEnabled = true;
         System.Data.Entity.Database.SetInitializer<EFModel1>(new EFModel1DatabaseInitializer());
         CustomInit();
      }

      /// <inheritdoc />
      public EFModel1(System.Data.Common.DbConnection existingConnection, System.Data.Entity.Infrastructure.DbCompiledModel model, bool contextOwnsConnection) : base(existingConnection, model, contextOwnsConnection)
      {
         Configuration.LazyLoadingEnabled = true;
         Configuration.ProxyCreationEnabled = true;
         System.Data.Entity.Database.SetInitializer<EFModel1>(new EFModel1DatabaseInitializer());
         CustomInit();
      }

      /// <inheritdoc />
      public EFModel1(System.Data.Entity.Infrastructure.DbCompiledModel model) : base(model)
      {
         Configuration.LazyLoadingEnabled = true;
         Configuration.ProxyCreationEnabled = true;
         System.Data.Entity.Database.SetInitializer<EFModel1>(new EFModel1DatabaseInitializer());
         CustomInit();
      }

      /// <inheritdoc />
      public EFModel1(System.Data.Entity.Core.Objects.ObjectContext objectContext, bool dbContextOwnsObjectContext) : base(objectContext, dbContextOwnsObjectContext)
      {
         Configuration.LazyLoadingEnabled = true;
         Configuration.ProxyCreationEnabled = true;
         System.Data.Entity.Database.SetInitializer<EFModel1>(new EFModel1DatabaseInitializer());
         CustomInit();
      }

      #endregion Constructors

      partial void OnModelCreatingImpl(System.Data.Entity.DbModelBuilder modelBuilder);
      partial void OnModelCreatedImpl(System.Data.Entity.DbModelBuilder modelBuilder);

      /// <inheritdoc />
      protected override void OnModelCreating(System.Data.Entity.DbModelBuilder modelBuilder)
      {
         base.OnModelCreating(modelBuilder);
         OnModelCreatingImpl(modelBuilder);

         modelBuilder.HasDefaultSchema("dbo");

         modelBuilder.Entity<global::SRUL.CountryInformation>()
                     .ToTable("CountryInformations")
                     .HasKey(t => t.Name);
         modelBuilder.Entity<global::SRUL.CountryInformation>()
                     .Property(t => t.Name)
                     .IsRequired()
                     .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);

         modelBuilder.Entity<global::SRUL.Games>()
                     .ToTable("Games")
                     .HasKey(t => t.Name);
         modelBuilder.Entity<global::SRUL.Games>()
                     .Property(t => t.Name)
                     .IsRequired()
                     .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
         modelBuilder.Entity<global::SRUL.Games>()
                     .HasMany(x => x.Versions)
                     .WithRequired()
                     .Map(x => x.MapKey("Games.Versions_Name"));

         modelBuilder.Entity<global::SRUL.Offset>()
                     .ToTable("Offsets")
                     .HasKey(t => t.Id);
         modelBuilder.Entity<global::SRUL.Offset>()
                     .Property(t => t.Id)
                     .IsRequired()
                     .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
         modelBuilder.Entity<global::SRUL.Offset>()
                     .HasRequired(x => x.UnitInformation)
                     .WithMany(x => x.Pointers)
                     .Map(x => x.MapKey("UnitInformation_UnitID"));

         modelBuilder.Entity<global::SRUL.Pointers>()
                     .ToTable("Pointers")
                     .HasKey(t => t.Id);
         modelBuilder.Entity<global::SRUL.Pointers>()
                     .Property(t => t.Id)
                     .IsRequired()
                     .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
         modelBuilder.Entity<global::SRUL.Pointers>()
                     .HasRequired(x => x.Versions)
                     .WithMany(x => x.Pointers)
                     .Map(x => x.MapKey("Versions_GameName"));
         modelBuilder.Entity<global::SRUL.Pointers>()
                     .HasRequired(x => x.Games)
                     .WithMany(x => x.Pointers)
                     .Map(x => x.MapKey("Games_Name"));

         modelBuilder.Entity<global::SRUL.UnitInformation>()
                     .ToTable("UnitInformations")
                     .HasKey(t => t.UnitID);
         modelBuilder.Entity<global::SRUL.UnitInformation>()
                     .Property(t => t.UnitID)
                     .IsRequired()
                     .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);

         modelBuilder.Entity<global::SRUL.Versions>()
                     .ToTable("Versions")
                     .HasKey(t => t.GameName);
         modelBuilder.Entity<global::SRUL.Versions>()
                     .Property(t => t.GameName)
                     .IsRequired()
                     .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);

         OnModelCreatedImpl(modelBuilder);
      }
   }
}
