//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor v
//     Source:                    https://github.com/msawczyn/EFDesigner
//     Visual Studio Marketplace: https://marketplace.visualstudio.com/items?itemName=michaelsawczyn.EFDesigner
//     Documentation:             https://msawczyn.github.io/EFDesigner/
//     License (MIT):             https://github.com/msawczyn/EFDesigner/blob/master/LICENSE
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.CompilerServices;

namespace SRUL
{
   public partial class UnitInformation
   {
      partial void Init();

      /// <summary>
      /// Default constructor
      /// </summary>
      public UnitInformation()
      {
         Pointers = new System.Collections.Generic.HashSet<global::SRUL.Offset>();

         Init();
      }

      /*************************************************************************
       * Properties
       *************************************************************************/

      /// <summary>
      /// Identity, Indexed, Required
      /// </summary>
      [Key]
      [Required]
      public int UnitID { get; protected set; }

      public string UnitName { get; set; }

      public string Property2 { get; set; }

      public string Property3 { get; set; }

      public string Property4 { get; set; }

      public string Property5 { get; set; }

      public string Property6 { get; set; }

      public string Property7 { get; set; }

      public string Property8 { get; set; }

      public string Property9 { get; set; }

      /*************************************************************************
       * Navigation properties
       *************************************************************************/

      public virtual ICollection<global::SRUL.Offset> Pointers { get; protected set; }

   }
}

